function obull = equinoctial_to_orbbull(equoes)
    if isfield(equoes, 'mean_longitude_deg')
        time_element_deg = equoes.mean_longitude_deg;
        time_element_type = st.mean_anomaly;
    else
        time_element_deg = equoes.true_longitude_deg;
        time_element_type = st.true_anomaly;
    end
    obull = ...
        struct('orbitBulletin', ...
	       struct('date', datestr(equoes.epoch, ori.iso8601_fmt_w), ...
		      'timeScale', "UTC", ...
		      'eciFrameName', ori.gcrf_s.frameName, ...
		      'equinoctial', struct('a', equoes.semimajor_axis_m,...
				         'ex', equoes.eccentricity_x,...
				         'ey', equoes.eccentricity_y,...
				         'hx', equoes.inclination_x,...
				         'hy', equoes.inclination_y,...
				         'l', deg2rad(time_element_deg),...
				         'positionAngle', time_element_type)));
end

%%================================================================================
%% Copyright 2022, 2023 Liam M. Healy
%% This file is part of SNaG-app.
%% SPDX-License-Identifier: GPL-3.0-or-later
