% Make a Kepler orbital element set for ORaaS
function orbels = kepler_to_orbbull(kepler_elements)
    if isfield(kepler_elements, 'mean_anomaly_deg')
        time_element_deg = kepler_elements.mean_anomaly_deg;
        time_element_type = st.mean_anomaly;
    else
        time_element_deg = kepler_elements.true_anomaly_deg;
        time_element_type = st.true_anomaly;
    end
    orbels = ...
        struct('orbitBulletin', ...
	       struct('date', datestr(kepler_elements.epoch, ori.iso8601_fmt_w), ...
		      'timeScale', "UTC", ...
		      'eciFrameName', ori.gcrf_s.frameName, ...
		      'keplerian', struct('a', kepler_elements.semimajor_axis_m,...
				          'e', kepler_elements.eccentricity,...
				          'i', deg2rad(kepler_elements.inclination_deg),...
				          'raan', deg2rad(kepler_elements.raan_deg),...
				          'pa', deg2rad(kepler_elements.argument_perigee_deg),...
				          'anomaly', deg2rad(time_element_deg),...
				          'positionAngle', time_element_type)));
end

%%================================================================================
%% Copyright 2020, 2021, 2022, 2023 Liam M. Healy
%% This file is part of SNaG-app.
%% SPDX-License-Identifier: GPL-3.0-or-later
