% Convert element set returned by ORaaS to SNaG-app representation
function converted=convels(orout, to_mean)
    epochdt = datetime_iso8601(orout.date);
    if isfield(orout,'cartesian')
        converted = or_pvt(epochdt, orout.cartesian);
        return;
    elseif isfield(orout,'keplerian')
        converted = kepler_oes(epochdt, orout.keplerian.a, orout.keplerian.e,...
                               rad2deg(orout.keplerian.i), rad2deg(orout.keplerian.raan), ...
                               rad2deg(orout.keplerian.pa),...
                               rad2deg(orout.keplerian.anomaly),...
                               to_mean);
        return;
    elseif isfield(orout,'circular')
        converted = circular_oes(epochdt, orout.circular.a, ...
                                 orout.circular.ex, orout.circular.ey, ...
                               rad2deg(orout.circular.i), rad2deg(orout.circular.raan), ...
                               rad2deg(orout.circular.alpha),...
                               to_mean);
        return;
    elseif isfield(orout,'equinoctial')
        converted = equinoctial_oes(epochdt, orout.equinoctial.a, ...
                                 orout.equinoctial.ex, orout.equinoctial.ey, ...
                                 orout.equinoctial.hx, orout.equinoctial.hy, ...
                               rad2deg(orout.equinoctial.l),...
                               to_mean);
        return;
    else
        error("Orbit conversion failed");
    end
end

%%================================================================================
%% Copyright 2022 Liam M. Healy
%% This file is part of SNaG-app.
%% SPDX-License-Identifier: GPL-3.0-or-later
